const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
const KEY='pcgpt-v1';let data=JSON.parse(localStorage.getItem(KEY)||'null')||{notes:[],sessions:0,days:[]};
const save=()=>localStorage.setItem(KEY,JSON.stringify(data));
const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)};
function clock(){const d=new Date();$('#clock').textContent=d.toLocaleTimeString('pt-BR');}setInterval(clock,1000);clock();
function render(){const list=$('#notesList');list.innerHTML=data.notes.length?data.notes.slice().reverse().map((n,i)=>`<div class="note"><div><p>${esc(n.text)}</p><small>${new Date(n.time).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</small></div><button data-del="${data.notes.length-1-i}" aria-label="Excluir">×</button></div>`).join(''):`<div class="output">Nenhuma nota ainda. Sua próxima ideia pode começar aqui.</div>`;$('#noteCount').textContent=data.notes.length;$('#sessionCount').textContent=data.sessions;const today=new Date().toDateString();$('#week').innerHTML=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);return `<i class="${data.days.includes(d.toDateString())?'active':''}" title="${d.toLocaleDateString('pt-BR',{weekday:'short'})}"></i>`}).join('');}
const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function openNote(){openModal(`<span class="label">NOVA IDEIA</span><h2>Capture antes de esquecer.</h2><textarea id="noteText" placeholder="Escreva qualquer coisa..."></textarea><button class="save" id="saveNote">Guardar</button>`);setTimeout(()=>$('#noteText').focus(),50);$('#saveNote').onclick=()=>{const text=$('#noteText').value.trim();if(!text)return toast('Escreva alguma coisa primeiro.');data.notes.push({text,time:Date.now()});save();render();closeModal();toast('Nota guardada localmente.');};}
function openModal(html){$('#modalContent').innerHTML=html;$('#modal').classList.add('open');$('#modal').setAttribute('aria-hidden','false')}function closeModal(){$('#modal').classList.remove('open');$('#modal').setAttribute('aria-hidden','true')}
$('#addNote').onclick=openNote;$('#closeModal').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};$('#notesList').onclick=e=>{const b=e.target.closest('[data-del]');if(b){data.notes.splice(+b.dataset.del,1);save();render();toast('Nota apagada.')}};
let remaining=1500,total=1500,running=false,interval=null,short=false;function paint(){const m=Math.floor(remaining/60),s=remaining%60;$('#timer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;$('#timerProgress').style.width=`${(1-remaining/total)*100}%`}
function toggleTimer(){running=!running;$('#startTimer').textContent=running?'Pausar':'Iniciar';if(running){interval=setInterval(()=>{remaining--;paint();if(remaining<=0){clearInterval(interval);running=false;$('#startTimer').textContent='Iniciar';data.sessions++;const t=new Date().toDateString();if(!data.days.includes(t))data.days.push(t);save();render();toast('Sessão concluída. Boa.');remaining=total;paint();}},1000)}else clearInterval(interval)}
$('#startTimer').onclick=toggleTimer;$('#resetTimer').onclick=()=>{clearInterval(interval);running=false;remaining=total;$('#startTimer').textContent='Iniciar';paint()};$('#modeTimer').onclick=()=>{short=!short;total=remaining=short?300:1500;$('#focusTitle').textContent=short?'Pausa curta':'Sessão livre';paint();toast(short?'Modo 5 minutos':'Modo 25 minutos')};paint();
function runCommand(raw){const c=raw.trim().toLowerCase();const out=$('#commandOutput');if(!c)return;if(c==='ajuda'||c==='help')out.innerHTML='Comandos: <b>hora</b>, <b>data</b>, <b>foco</b>, <b>nota</b>, <b>limpar</b>.';else if(c==='hora')out.textContent='Agora são '+new Date().toLocaleTimeString('pt-BR');else if(c==='data')out.textContent='Hoje é '+new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'});else if(c==='foco'){window.scrollTo({top:document.querySelector('.focus-card').offsetTop-90,behavior:'smooth'});out.textContent='Painel de foco localizado.'}else if(c==='nota')openNote();else if(c==='limpar'){$('#commandInput').value='';out.textContent='Console limpo.'}else out.textContent='Comando não reconhecido. Digite “ajuda”.';$('#commandInput').value='';}
$('#runCommand').onclick=()=>runCommand($('#commandInput').value);$('#commandInput').onkeydown=e=>{if(e.key==='Enter')runCommand(e.target.value)};$('#commandBtn').onclick=()=>{$('#commandInput').focus();window.scrollTo({top:document.querySelector('.command-card').offsetTop-90,behavior:'smooth'})};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#commandInput').focus()}});
$$('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='note')openNote();if(a==='calc'){$('#calcDisplay').focus();window.scrollTo({top:document.querySelector('.calc-card').offsetTop-90,behavior:'smooth'})}if(a==='search')window.open('https://www.google.com','_blank','noopener');if(a==='export'){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='pcgpt-backup.json';a.click();URL.revokeObjectURL(url);toast('Backup exportado.')}});
let expr='';const display=$('#calcDisplay');function calc(k){if(k==='C'){expr='';display.value='';return}if(k==='='){try{if(!/^[0-9+\-*/.() ]+$/.test(expr))throw Error();const result=Function(`"use strict";return (${expr})`)();expr=String(result);display.value=expr}catch{display.value='Erro';expr=''}return}expr+=k;display.value=expr}$$('[data-key]').forEach(b=>b.onclick=()=>calc(b.dataset.key));display.onkeydown=e=>{if(e.key==='Enter')calc('=');if(e.key==='Escape')calc('C')};
$('#clearData').onclick=()=>{if(confirm('Apagar todas as notas e sessões deste dispositivo?')){data={notes:[],sessions:0,days:[]};save();render();toast('Dados locais apagados.')}};$('#homeBtn').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});render();
