/* PCGPT value engine — local-first. No payment processing. */
(() => {
  const KEY='pcgpt-value-v5';
  const $=id=>document.getElementById(id);
  let state;
  try { state=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem('pcgpt-value-v4')||localStorage.getItem('pcgpt-value-v3')||localStorage.getItem('pcgpt-value-v2')||'null'); } catch { state=null; }
  state ||= {};
  const normalize=()=>{state.goal=Number(state.goal)||100;state.earned=Number(state.earned)||0;state.opportunities=Number(state.opportunities)||0;state.wins=Number(state.wins)||0;state.leads=Array.isArray(state.leads)?state.leads:[];state.pipeline=Array.isArray(state.pipeline)?state.pipeline:[];state.history=Array.isArray(state.history)?state.history:[];state.last=state.last||null};
  normalize();
  const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
  const money=n=>`R$ ${Number(n||0).toFixed(2).replace('.',',')}`;
  const esc=s=>String(s).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  const notify=m=>typeof window.toast==='function'?window.toast(m):void 0;
  const log=(type,label,value=0,meta={})=>{state.history.push({id:Date.now().toString(36)+Math.random().toString(36).slice(2,6),type,label,value:Number(value)||0,time:Date.now(),...meta});if(state.history.length>200)state.history=state.history.slice(-200);state.last=Date.now();save()};
  const todayStart=()=>{const d=new Date();d.setHours(0,0,0,0);return d.getTime()};
  const recentEarned=()=>state.history.filter(x=>x.type==='earned'&&x.time>=todayStart()).reduce((s,x)=>s+x.value,0);
  function panel(){
    if($('value-engine')) return;
    const wrap=document.createElement('section');wrap.id='value-engine';wrap.className='card';
    wrap.innerHTML=`<div class="card-head"><div><span class="label">OPERADOR LOCAL</span><h2>Encontre, filtre e acompanhe valor</h2></div><button class="add" id="ve-settings" title="Configurar meta">⚙</button></div><p class="muted">O PCGPT organiza oportunidades e prepara trabalho localmente. Ele não finge ser você, não burla regras e não processa pagamentos.</p><div class="value-stats"><div><small>Meta</small><strong id="ve-goal"></strong></div><div><small>Recebido</small><strong id="ve-earned"></strong></div><div><small>Hoje</small><strong id="ve-today"></strong></div><div><small>Oportunidades</small><strong id="ve-opp"></strong></div></div><div class="value-progress"><span id="ve-progress"></span></div><div class="value-actions"><button class="btn primary" id="ve-intake">+ receber tarefa</button><button class="btn" id="ve-opportunity">+ oportunidade</button><button class="btn" id="ve-earned-btn">+ ganho real</button><button class="btn" id="ve-new-pipeline">+ fluxo</button><button class="btn" id="ve-export">backup</button><button class="btn" id="ve-import">restaurar</button></div><div id="ve-operator" class="value-leads"></div><div id="ve-pipeline" class="value-leads"></div><div id="ve-history" class="value-leads"></div>`;
    const anchor=[...document.querySelectorAll('.card')].find(x=>/Sinal do Sistema/i.test(x.textContent));(anchor?.parentElement||document.querySelector('main')||document.body).appendChild(wrap);
    $('ve-settings').onclick=()=>{const raw=prompt('Qual é sua meta de dinheiro? (R$)',String(state.goal).replace('.',','));if(raw===null)return;const n=Number(String(raw).replace(',','.'));if(Number.isFinite(n)&&n>0){state.goal=n;log('goal','Meta alterada',0,{goal:n});render();notify(`Meta definida em ${money(n)}.`)}else notify('Meta inválida.')};
    $('ve-opportunity').onclick=()=>{state.opportunities++;log('opportunity','Oportunidade registrada');render();notify('Oportunidade registrada.')};
    $('ve-earned-btn').onclick=()=>{const raw=prompt('Quanto entrou de verdade? (R$)');const n=Number(String(raw||'').replace(',','.'));if(Number.isFinite(n)&&n>0){state.earned+=n;state.wins++;log('earned','Ganho real',n);render();notify(`${money(n)} registrado como ganho real.`)}};
    $('ve-intake').onclick=()=>{const task=prompt('Cole ou escreva a tarefa recebida:');if(!task?.trim())return;const t=task.trim(),lower=t.toLowerCase();let verdict='REVISAR',reason='Precisa de análise antes de executar.';if(/senha|cpf|cartão|cartao|código de acesso|codigo de acesso|login de terceiro|documento oficial/i.test(t)){verdict='BLOQUEAR';reason='Envolve credenciais, identidade ou dado sensível.'}else if(/fingir|mentir|burlar|enganar|spam|captcha|idade mínima|idade minima|menor de idade/i.test(t)){verdict='BLOQUEAR';reason='A tarefa pede engano, automação protegida ou contorno de regra.'}else if(/pesquisa|questionário|questionario|responder|classificar|organizar|texto|resumir|calcular|planilha|dados/i.test(lower)){verdict='PREPARAR';reason='Parece adequada para assistência local, mas as regras do serviço precisam permitir automação.'}state.pipeline.push({id:Date.now().toString(36)+Math.random().toString(36).slice(2,6),title:t.slice(0,180),value:0,status:verdict==='PREPARAR'?1:0,verdict,reason,time:Date.now(),completed:false});state.opportunities++;log('intake','Tarefa recebida',0,{verdict});render();notify(`Tarefa recebida: ${verdict}.`)};
    $('ve-new-pipeline').onclick=()=>{const title=prompt('O que você quer acompanhar?');if(!title?.trim())return;const raw=prompt('Valor potencial (opcional, R$)','0');const value=Number(String(raw||0).replace(',','.'));state.pipeline.push({id:Date.now().toString(36)+Math.random().toString(36).slice(2,6),title:title.trim(),value:Number.isFinite(value)&&value>0?value:0,status:0,verdict:'REVISAR',reason:'Registro manual.',time:Date.now(),completed:false});state.opportunities++;log('pipeline','Item criado');render();notify('Item adicionado ao fluxo.')};
    $('ve-export').onclick=()=>{const payload={format:'PCGPT backup',version:5,exportedAt:new Date().toISOString(),state};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='pcgpt-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);notify('Backup exportado.')};
    $('ve-import').onclick=()=>{const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=()=>{const file=input.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const raw=JSON.parse(reader.result),s=raw.state||raw;if(!s||!Array.isArray(s.pipeline)||!Array.isArray(s.history))throw Error();if(!confirm('Substituir os dados de valor deste dispositivo pelo backup?'))return;state={...s};normalize();save();render();notify('Backup restaurado.')}catch{notify('Backup inválido.')}};reader.readAsText(file)};input.click()};
  }
  function render(){panel();const g=$('ve-goal'),e=$('ve-earned'),o=$('ve-opp'),t=$('ve-today'),p=$('ve-progress'),pipe=$('ve-pipeline'),hist=$('ve-history'),op=$('ve-operator');if(g)g.textContent=money(state.goal);if(e)e.textContent=money(state.earned);if(o)o.textContent=state.opportunities;if(t)t.textContent=money(recentEarned());if(p)p.style.width=`${Math.min(100,state.goal>0?(state.earned/state.goal)*100:0)}%`;
    if(op)op.innerHTML=`<div class="label" style="margin:16px 0 8px">REGRAS DO OPERADOR</div><div class="output">✓ Pode preparar, classificar, calcular e organizar tarefas permitidas.<br>✓ Pode registrar resultados e ganhos reais.<br>× Não usa credenciais de terceiros, não inventa respostas e não contorna idade, CAPTCHA ou regras de plataformas.</div>`;
    if(pipe)pipe.innerHTML=state.pipeline.length?`<div class="label" style="margin:16px 0 8px">FLUXO</div>`+state.pipeline.slice(-8).reverse().map(x=>{const labels=['revisar','preparar','contato','resultado'];const status=x.completed?'concluído':(x.verdict==='BLOQUEAR'?'bloqueado':labels[Math.min(3,x.status||0)]);return `<div class="output" style="display:flex;gap:8px;align-items:center;justify-content:space-between;flex-wrap:wrap"><span><b>${esc(x.title)}</b>${x.value?` · ${money(x.value)}`:''}<small> · ${status}${x.verdict==='BLOQUEAR'?` · ${esc(x.reason)}`:''}</small></span><span style="display:flex;gap:5px"><button class="btn" data-ve-next="${x.id}" ${x.completed||x.verdict==='BLOQUEAR'?'disabled':''}>→</button><button class="btn" data-ve-del="${x.id}">×</button></span></div>`}).join(''):'<div class="output">Nenhuma tarefa no fluxo ainda.</div>';
    if(hist){const recent=state.history.slice(-6).reverse();hist.innerHTML=recent.length?`<div class="label" style="margin:16px 0 8px">ÚLTIMOS EVENTOS</div>`+recent.map(x=>`<div class="output">${esc(x.label)}${x.value?` · ${money(x.value)}`:''}<small> · ${new Date(x.time).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</small></div>`).join(''):''}
    pipe?.querySelectorAll('[data-ve-next]').forEach(b=>b.onclick=()=>{const x=state.pipeline.find(v=>v.id===b.dataset.veNext);if(!x||x.completed||x.verdict==='BLOQUEAR')return;x.status=Math.min(3,(x.status||0)+1);if(x.status>=3)x.completed=true;log('pipeline','Fluxo avançado');render();notify(x.completed?'Resultado concluído.':'Fluxo avançado.')});
    pipe?.querySelectorAll('[data-ve-del]').forEach(b=>b.onclick=()=>{state.pipeline=state.pipeline.filter(v=>v.id!==b.dataset.veDel);log('pipeline','Item removido');render();notify('Item removido.')});
  }
  const api={save,render,reset:()=>{state={goal:100,earned:0,opportunities:0,wins:0,leads:[],pipeline:[],history:[],last:null};save();render()}};Object.defineProperty(api,'state',{get:()=>state});window.PCGPTValue=api;
  window.addEventListener('load',render);window.setTimeout(render,500);
})();
