/* PCGPT operator — local-first orchestration. It never impersonates a user or bypasses site rules. */
(() => {
  const KEY='pcgpt-operator-v5',OLD='pcgpt-operator-v4',OLD2='pcgpt-operator-v3',OLD3='pcgpt-operator-v2',OLD4='pcgpt-operator-v1';
  const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const notify=m=>typeof window.toast==='function'?window.toast(m):void 0;
  let state;try{state=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem(OLD)||localStorage.getItem(OLD2)||localStorage.getItem(OLD3)||localStorage.getItem(OLD4)||'null')}catch{state=null}
  state ||= {name:'',auto:false,queue:[],runs:0,blocked:0,done:0,history:[]};state.queue ||= [];state.history ||= [];
  const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
  const classify=text=>{const t=text.toLowerCase();if(/captcha|recaptcha|senha|password|2fa|código de verificação|verification code|idade mínima|menor de idade|documento oficial|cartão|cartao|cpf/.test(t))return['BLOQUEAR','Requer credencial, dado sensível ou verificação protegida.'];if(/fingir|mentir|burlar|enganar|spam|fraude|contornar regra/.test(t))return['BLOQUEAR','Pede engano ou contorno de regra.'];if(/pesquisa|survey|questionário|questionario|opinião|responder|classificar/.test(t))return['REVISAR','Pode envolver respostas pessoais; o operador prepara, você confirma.'];if(/pesquise|compare|liste|resuma|organize|calcule|converta|texto|planilha|dados|transcreva|formate|extraia/.test(t))return['PREPARAR','Tarefa estruturada que pode ser transformada em um pacote de trabalho local.'];return['REVISAR','A tarefa não foi reconhecida com segurança suficiente para execução automática.']};
  const makePacket=(text,name)=>{const t=text.toLowerCase();let type='PLANO';let steps=['Entender o objetivo','Separar dados necessários','Produzir uma primeira versão','Revisar antes de entregar'];if(/pesquisa|survey|questionário|questionario/.test(t)){type='PESQUISA ASSISTIDA';steps=['Identificar perguntas','Separar fatos de respostas pessoais','Preparar rascunho sem inventar dados','Você revisa e envia'];}else if(/resum|texto|transcri/.test(t)){type='TEXTO';steps=['Identificar conteúdo de origem','Estruturar os pontos principais','Gerar rascunho','Você revisa o resultado'];}else if(/calcule|converter|cálculo|calculo/.test(t)){type='CÁLCULO';steps=['Extrair números e unidades','Calcular com método verificável','Mostrar resultado','Você confere antes de usar'];}else if(/planilha|dados|liste|organize|extra/.test(t)){type='DADOS';steps=['Definir campos','Normalizar informações','Organizar saída','Você valida os dados'];}return{type,steps,identity:name||'não definida',createdAt:new Date().toISOString()}};
  function panel(){if($('#operator'))return;const wrap=document.createElement('section');wrap.id='operator';wrap.className='card';wrap.innerHTML=`<div class="card-head"><div><span class="label">OPERADOR</span><h2>Fila de trabalho</h2></div><span class="pulse">◉</span></div><p class="muted">Receba uma tarefa, filtre riscos e gere um pacote de execução local. Envio e decisões pessoais continuam sob seu controle.</p><div class="operator-top"><input id="opName" class="task-input" placeholder="Seu nome de trabalho (opcional)" value="${esc(state.name)}"><label class="op-toggle"><input id="opAuto" type="checkbox" ${state.auto?'checked':''}> modo automático local</label></div><div class="command-line"><span>›</span><input id="opInput" autocomplete="off" placeholder="Cole uma oportunidade ou tarefa..."><button id="opAdd">ANALISAR</button></div><div class="op-bulk"><button class="btn" id="opRunAll">PROCESSAR SEGUROS</button><button class="btn" id="opExport">EXPORTAR PACOTES</button><button class="btn" id="opClearDone">LIMPAR PROCESSADAS</button></div><div class="value-stats"><div><small>Fila</small><strong id="opQueue">0</strong></div><div><small>Preparadas</small><strong id="opDone">0</strong></div><div><small>Bloqueadas</small><strong id="opBlocked">0</strong></div><div><small>Execuções</small><strong id="opRuns">0</strong></div></div><div id="opList" class="value-leads"></div>`;const anchor=[...document.querySelectorAll('.card')].find(x=>/Sinal do Sistema/i.test(x.textContent));(anchor?.parentElement||document.querySelector('main')).appendChild(wrap);$('#opName').oninput=e=>{state.name=e.target.value.slice(0,80);save()};$('#opAuto').onchange=e=>{state.auto=e.target.checked;save();notify(state.auto?'Modo automático local ligado.':'Modo automático local desligado.')};$('#opAdd').onclick=()=>add($('#opInput').value);$('#opInput').onkeydown=e=>{if(e.key==='Enter')add(e.target.value)};$('#opRunAll').onclick=runAll;$('#opExport').onclick=exportPackets;$('#opClearDone').onclick=clearDone}
  function add(raw){const text=raw.trim();if(!text)return notify('Cole uma tarefa primeiro.');const[kind,reason]=classify(text);const item={id:Date.now().toString(36)+Math.random().toString(36).slice(2,6),text,kind,reason,time:Date.now(),status:'fila',packet:null};state.queue.push(item);if(kind==='BLOQUEAR')state.blocked++;save();render();$('#opInput').value='';notify(kind==='BLOQUEAR'?'Ação bloqueada.':'Tarefa analisada.');if(state.auto&&kind==='PREPARAR')prepare(item.id)}
  function prepare(id){const x=state.queue.find(v=>v.id===id);if(!x||x.kind!=='PREPARAR'||x.status==='feito')return;x.status='feito';x.packet=makePacket(x.text,state.name);state.done++;state.runs++;state.history.push({type:'run',label:x.text.slice(0,100),time:Date.now()});if(state.history.length>100)state.history=state.history.slice(-100);save();render();notify('Pacote de trabalho preparado.')}
  function runAll(){const ids=state.queue.filter(x=>x.kind==='PREPARAR'&&x.status==='fila').map(x=>x.id);ids.forEach(prepare);if(ids.length)notify(`${ids.length} tarefa(s) processada(s) com segurança.`);else notify('Nenhuma tarefa segura na fila.')}
  function clearDone(){const n=state.queue.filter(x=>x.status==='feito').length;state.queue=state.queue.filter(x=>x.status!=='feito');save();render();notify(n?`${n} pacote(s) removido(s) da fila.`:'Nenhum pacote processado para limpar.')}
  function exportPackets(){const packets=state.queue.filter(x=>x.packet).map(x=>({tarefa:x.text,tipo:x.packet.type,passos:x.packet.steps,identidade:x.packet.identity,criado:x.packet.createdAt}));if(!packets.length)return notify('Ainda não há pacotes para exportar.');const text=JSON.stringify({exportado:new Date().toISOString(),pacotes:packets},null,2);navigator.clipboard?.writeText(text).then(()=>notify('Pacotes copiados para a área de transferência.')).catch(()=>notify('Exportação pronta; use o histórico local.'))}
  function remove(id){state.queue=state.queue.filter(v=>v.id!==id);save();render()}
  function reset(){state={name:'',auto:false,queue:[],runs:0,blocked:0,done:0,history:[]};save();render()}
  function render(){panel();$('#opQueue').textContent=state.queue.filter(x=>x.status==='fila').length;$('#opDone').textContent=state.done;$('#opBlocked').textContent=state.blocked;$('#opRuns').textContent=state.runs;const list=$('#opList');if(!list)return;list.innerHTML=state.queue.slice(-10).reverse().map(x=>{const cls=x.kind==='BLOQUEAR'?'blocked':x.kind==='PREPARAR'?'ready':'review';const packet=x.packet?`<div class="output"><b>${esc(x.packet.type)}</b><br>${x.packet.steps.map((s,i)=>`${i+1}. ${esc(s)}`).join('<br>')}<br><small>Identidade informada: ${esc(x.packet.identity)}</small></div>`:'';return `<div class="output op-item ${cls}"><div><b>${esc(x.kind)}</b> · ${esc(x.text.slice(0,180))}<br><small>${esc(x.reason)}</small></div>${packet}<div class="op-actions">${x.kind==='PREPARAR'&&x.status==='fila'?`<button class="btn" data-op-run="${x.id}">preparar</button>`:''}<button class="btn" data-op-del="${x.id}">×</button></div></div>`}).join('')||'<div class="output">Fila vazia. O operador está esperando trabalho.</div>';list.querySelectorAll('[data-op-run]').forEach(b=>b.onclick=()=>prepare(b.dataset.opRun));list.querySelectorAll('[data-op-del]').forEach(b=>b.onclick=()=>remove(b.dataset.opDel));save()}
  window.PCGPTOperator={state,add,prepare,runAll,clearDone,exportPackets,reset,render,save};window.addEventListener('load',render);setTimeout(render,700);
})();
